# Generated by Django 3.2.13 on 2022-06-01 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='Дедлайн')),
                ('priority', models.CharField(blank=True, choices=[('Важно', 'Важно'), ('Нормально', 'Нормально'), ('Неважно', 'Неважно')], max_length=9, verbose_name='Приоритет')),
                ('employers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks',
            },
        ),
    ]
