# Generated by Django 3.2.13 on 2022-06-01 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lifedo_services', '0002_alter_taskmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание задачи'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='employers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(blank=True, choices=[('Важно', 'Важно'), ('Нормально', 'Нормально'), ('Неважно', 'Неважно')], max_length=9, null=True, verbose_name='Приоритет'),
        ),
    ]
