# Generated by Django 3.2.13 on 2022-06-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifedo_services', '0003_auto_20220601_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'verbose_name': 'задачу', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='progress',
            field=models.CharField(blank=True, choices=[('Завершено', 'Завершено'), ('В процессе', 'В процессе'), ('Заброшено', 'Заброшено')], max_length=10, null=True, verbose_name='Состояние'),
        ),
    ]
