# Generated by Django 3.2.13 on 2022-06-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifedo_services', '0004_auto_20220601_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='progress',
            field=models.CharField(choices=[('Завершено', 'Завершено'), ('В процессе', 'В процессе'), ('Заброшено', 'Заброшено')], default='В процессе', max_length=10, verbose_name='Состояние'),
        ),
    ]
