# Generated by Django 3.2.13 on 2022-06-01 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lifedo_services', '0005_alter_taskmodel_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='employers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
    ]
